### ISSUE TITLE
Add posibility to maximize timeline (fullscreen mode)

### ISSUE THREAD

**Issue by ilnytskyi** [NoiseByNorthwest/php-spx#100]
I found this very usefull.
It would be good to have buttons on wigests to maximize and minimize view.
For example, just removed bottom wigests.
![image](https://user-images.githubusercontent.com/3192770/71113812-ae54e400-21ce-11ea-9471-3350c5286736.png)
I could contribute, however I need some tips where to begin ?
Add buttons here
https://github.com/NoiseByNorthwest/php-spx/blob/master/assets/web-ui/report.html#L31
or modify the widgets 
https://github.com/NoiseByNorthwest/php-spx/blob/master/assets/web-ui/report.html#L245

**Comment by NoiseByNorthwest** [comment]
I agree it would be useful. Your contribution is, of course, welcome.
What I would do is something like extending the widget class here https://github.com/NoiseByNorthwest/php-spx/blob/master/assets/web-ui/js/widget.js#L383
in order to create a new abstract widget type (say MaximizableWidget), this one adding the maximize/restore behaviors. Then you will just have to make the desired concrete widget types inheriting from MaximizableWidget instead of Widget to make them able to be maximized.

To handle the maximizing, on way to do this maybe to pass an additional DOM node container to the constructor, say maximizingContainer, having the max size & being hidden by default. On maximize, the trick would be to show this container and use it for rendering in place of the one referenced by the "container" property.

**Comment by NoiseByNorthwest** [comment]
@ilnytskyi I'll do it.

**Comment by NoiseByNorthwest** [comment]
@ilnytskyi Since the merging of #104 it is now possible to adjust the layout (i.e. the size of timeline, flat profile & Flamegraph widgets) via 2 layout splitters.
I've chosen this option as it is simpler to implement than the maximizing feature.

Youn can try it here: https://noisebynorthwest.github.io/php-spx/demo/report.html?key=spx-full-20191229_175636-06d2fe5ee423-3795-233665123

For instance, here is how you can increase the timeline's height via the horizontal layout splitter above the timeline.

![image](https://user-images.githubusercontent.com/1461284/71561162-3068c680-2a73-11ea-8495-f82b23b6dfec.png)

**Comment by ilnytskyi** [comment]
@NoiseByNorthwest 
Wow, thanks.
It works well
Good solution !

**Comment by NoiseByNorthwest** [comment]
@ilnytskyi thanks for your feedback. Can this issue be closed ?
