### ISSUE TITLE
opcache impact on SPX profiling?

### ISSUE THREAD

**Issue by 8ctopus** [NoiseByNorthwest/php-spx#149]
Hello Sylvain,

I've tested SPX profiling of php scripts with and without opcache.

The scripts are faster when opcache is enabled, however I expected SPX not to work when the script is cached by opcache (eg. reload of the same script). I would be grateful if you could comment on how SPX and opcache interact?

**Comment by NoiseByNorthwest** [comment]
Hi,

SPX does work with OPcache since they do not interact between each other.

OPcache only caches the output of a PHP script compilation which is roughly an array of low level operations. It also has some extra optimization stages. But AFAIK there is no optimization which involves the replacement of a function call.
Thus OPcache does not do anything during the script's execution and does not change the compiled scripts in terms of called functions.

SPX, for its part, works by intercepting function calls during the script's execution.

Furthermore SPX allows to confirm that OPcache is working as expected.
To do so, profile a script with internal functions traced. Without OPcache enabled you should see a larger amount of time spent in `::zend_compile_file` than with OPcache enabled and its cache warmed up.

**Comment by 8ctopus** [comment]
Thank you for taking the time to explain it :)
