### ISSUE TITLE
Allow naming profiles

### ISSUE THREAD

**Issue by ruudk** [NoiseByNorthwest/php-spx#173]
Often I want to name certain profiles. For example "Main branch", "Feature branch" to spot the differences. 

Would be great if there was a way to pass the profile name via `SPX_PROFILE_NAME` or to make it possible to rename existing profiles in the Web UI.

**Comment by NoiseByNorthwest** [comment]
In fact I was already considering the addition of a tag support which seems to also satisfy your use case.
Because instead of building a name from a characteristic or a list of characteristics (a branch is a characteristic that could be shared by many profiles) why not simply add a way to specify these characteristics ?

A tag list with  a `<key>:<value>` format a la opentracing would do the job.

Then in your case you would just have to add in your command line prefix this env var: `SPX_TAGS=branch:main,<other tags...>`.

This tag support is also already required for the "tasks processor" use case where a single PHP script generates many profiling reports (via `spx_profiler_start()` & `spx_profiler_stop()`). There is indeed currently no way to easily distinguish one task processing report from another one of the same process.

**Comment by ruudk** [comment]
That would be even better indeed!
