### ISSUE TITLE
Improve macOS timer resolution

### ISSUE THREAD

**Issue by NoiseByNorthwest** [NoiseByNorthwest/php-spx#30]
With mach_absolute_time() as in http://svn.php.net/viewvc/pecl/hrtime/trunk/timer.c?revision=333366&view=markup

@orls what is your opinion about that?

**Comment by orls** [comment]
I think that'll be usable for wall time, but the on-cpu time will still be microseconds multiplied up – not sure if you'd consider that a problem?

I'll have a go at this soon. I've been meaning to check out the new UI anyway. (It looks amazing, btw!)

**Comment by orls** [comment]
Indeed (If you recall, in my initial impl I [polyfilled it for < 10.12](https://github.com/NoiseByNorthwest/php-spx/pull/13/files#diff-3c18eca349aee651dc97ec51ba0f903eR4) because it was called globally, but then you [consolidated](https://github.com/NoiseByNorthwest/php-spx/commit/8746628e31abd8e862542229637e3d239b2490c6) all timing into `spx_resource_stats-...`).

It looks like it supports `CLOCK_PROCESS_CPUTIME_ID` too, which is great.

Personally I'd like to keep compatibility for 10.11, at least for now (colleagues & special snowflakes)...so how about I implement nsec resolution using `clock_gettime` for 10.12+ and fall back to usec for <= 10.11? The fallback mess will be isolated to only `spx_resource_stats-macos.c`.

**Comment by NoiseByNorthwest** [comment]
Yes, this is what I was thinking about.
I do not want to break compatibility with 10.11-, but we can do OS version dispatching (confined to spx_resource_stats-macos.c as you said or even subfiles if implementations are totally differents) to implement the optimal clock for each version.

**Comment by NoiseByNorthwest** [comment]
Fixed by #36
