### ISSUE TITLE
support flamegraph compatible output format 

### ISSUE THREAD

**Issue by Slach** [NoiseByNorthwest/php-spx#5]
Can your profiler output in Brandon Gregg https://github.com/brendangregg/FlameGraph compatible? With __FILE__ and __LINE__ ? Like a Uber https://github.com/uber/pyflame?

**Comment by NoiseByNorthwest** [comment]
Hello,

Thanks for this suggestion!

I'm currently working on a built-in web UI which will be the place for any custom visualization, and indeed, Flame Graph could possibly be added.

But the first available visualization will be an interactive time line alongside graphs for all monitored metrics since, IMO, it covers much more use cases.

So discussion on this feature request should be postponed to the release of the web UI (late October).

**Comment by NoiseByNorthwest** [comment]
Hello,

Flame graph will be part of the future embedded web UI, covered by #12.
Nevertheless only function names will be displayed since file/line is not relevant IMO to qualify a stack frame. It could be changed later if it appears to be relevant or if a trade-off is found (like a popover).
