### ISSUE TITLE
WebUI not showing exclusive time properly when zoomed in

### ISSUE THREAD

**Issue by jrgilman** [NoiseByNorthwest/php-spx#65]
As the title says, take a look at this [screenshot](https://imgur.com/a/4Vz3tBs) when zoomed in very closely. You'll notice that it's ordered by exclusive wall time, and buildInserts is at the top. But when you look at the gaps between the two calls to addPriceDatum, the time difference is around 15ms for buildIterator doing something. Shouldn't buildIterator be the third-ish entry on the function list?

[But when zoomed out fully, buildIterator's exclusive time suddenly shows up properly.](https://imgur.com/a/21JI9gv)

Any ideas?

**Comment by NoiseByNorthwest** [comment]
Yes, flat profile & Flamegraph seems to be OK as they are consistent between each other.
According to the Flamegraph view buildIterator consumes roughly 1/3 on its own so 35% exc time is consistent.

What seems to be broken here is the timeline (as well as overview) due to some numerical limits reached (see the NaNs in time grid) between 800s and 1000s. Strange since 1000s is only a thousand billions nanoseconds.

I will investigate that.

**Comment by jrgilman** [comment]
I just realized that this isn't a bug. I re-ran with FP_FULL_RES=0 rather than 15 and it was able to catch the work that was being done between the two large events.
