### ISSUE TITLE
PHP Process Can't Open /proc/self/task/XX/io

### ISSUE THREAD

**Issue by Qwokka** [NoiseByNorthwest/php-spx#89]
Hello,

I'm trying to use php-spx to track IO usage of a script. This works fine from the PHP cli but fails when run a webserver. The problem is that the PHP child process isn't allowed to open /proc/self/task/XX/io (Or /proc/self/io for that matter).

I've tested this with apache + mod_php and nginx + php-fpm. One working configuration I've found is running the php-fpm service as root, which is totally fine for my purposes but obviously not ideal. I would guess it could also work to run apache as root, but I haven't tried.

Is there a particular configuration you recommend?

Thanks!

**Comment by NoiseByNorthwest** [comment]
For PHP-FPM you should try this setting: `process.dumpable = yes`.

The root ownership of `/proc/self` is a consequence of the loss of dumpable attribute. As far as I understand from the [detailed responses here](https://stackoverflow.com/questions/50863306/cannot-open-proc-self-oom-score-adj-when-i-have-the-right-capability), for PHP-FPM case, it could be due to the user/group stepdown of a master pool process (as configured in the corresponding pool conf).

**Comment by Qwokka** [comment]
Thanks for the quick response!

Setting `process.dumpable` in the pool config (In my case `/etc/php/7.2/fpm/pool.d/www.conf`) does fix the problem for me.

**Comment by NoiseByNorthwest** [comment]
Nice! Thanks for your feedback.
