### ISSUE TITLE
phpStorm doesn`t handle xDebug remote debbuging when php-spx is installed

### ISSUE THREAD

**Issue by SergeyRock** [NoiseByNorthwest/php-spx#97]
Hello,
xDebug works fine when I remove linking php-spx from php settings file.

**Comment by orls** [comment]
I’ve encountered this before as well. It’s been a while since I used spx, but from memory, xdebug works until the first spx initialisation, and then stops working until the php process restarts.

I think this might be to do with the way spx adds “hooks”/wrappers around zend engine internals, I.e accidentally stomps/disables equivalent xdebug hooks.

**Comment by NoiseByNorthwest** [comment]
I agree @orls, this has certainly something to do with execution hooks manipulation. This is the only way Xdebug & SPX can interfere between each other.

But AFAIK what it is currently done is safe regarding what Xdebug does.
Let me explain why:
- Xdebug handles zend execution hooks wrapping at module init/shutdown.
- SPX does it at request init/shutdown, and if needed only (i.e. to profile the current script or to serve its UI).

And even if Xdebug would have handled them at request boundaries, the init & shutdown handlers ordering are reversed as expected. So no nasty overlap could happen.

Also, since hooks are globals, they cannot be touched safely in ZTS context, but SPX does not support ZTS and if it would support it, hooks manipulation would happen at module boundaries.

This issue sounds like SPX does not get (at rinit) or restore (at rshutdown) the correct hooks values.

I'll try to reproduce it.

**Comment by NoiseByNorthwest** [comment]
I've reproduced it, and quickly found the cause, just a kind of typo. Instead of wrapping the current hook value I was wrapping the original Zend execution handler, thus removing originally present wrappers.
